### ISSUE TITLE
Issue with building it

### ISSUE THREAD

**Issue by RYG81** [jam3sward/quadifier#10]
![quadifier_error](https://cloud.githubusercontent.com/assets/10570236/25703060/95af5474-30f1-11e7-9e01-22275f74d284.JPG)

Getting this error when trying to build through Visual Studio 2015
Please help

**Comment by RYG81** [comment]
Any one checking the problem?

**Comment by jam3sward** [comment]
Hi, it can't find the Direct3D library - have you got the DirectX SDK
installed?
Regards
James

**Comment by RYG81** [comment]
Yes,
I have installed it.
I am not sure why it is not detecting the path.
Do you have release available in source? Or can you help on how to over come this issue.
Rahul

**Comment by RYG81** [comment]
Hi James.
Do you have build release version of this?

Rahul

**Comment by jam3sward** [comment]
Hi there. In Visual Studio try the following:
- Open "Property Manager", right-click on "module" and select "Properties"
- Make sure "All Configurations" is selected
- Go to "Linker" then "General" and check that "Additional Library Directories" includes the correct path to the location of your Microsoft DirectX SDK library directory.
For example: "C:\Microsoft DirectX SDK (June 2010)\Lib\x86"

**Comment by jam3sward** [comment]
Closing this as a technical support case (rather than an issue with the software). We can continue discussion on here if you are still stuck though!
