### ISSUE TITLE
Is this limited to nvidia cards?

### ISSUE THREAD

**Issue by RYG81** [jam3sward/quadifier#11]
**FROM THE DESCRIPTION**
Most of the work is carried out by the Quadifier class. It causes Direct3D
to render into a render target instead of the screen. The corresponding
surface is mapped onto an OpenGL texture or renderbuffer using the **NVIDIA
NV_DX_interop extension**. This is attached to a framebuffer object. The
framebuffer object is blitted to the back left or back right OpenGL render
buffers as appropriate.

Is this limited to nvidia cards only?

**Comment by jam3sward** [comment]
It will probably work on some stereo capable AMD cards. My colleague Jason
made some changes for compatibility with ATI/AMD (and his changes are
incorporated in the current version here on Github), so in theory it should
work. Personally, I've only used it on NVIDIA, so I don't have any direct
experience with AMD to share.
I seem to remember that Jason did get it working on AMD though.

**Comment by jam3sward** [comment]
I spoke to Jason today and he confirmed that he did have Quadifier working on an AMD card, although he no longer has that card available for testing. I'm closing this ticket, but would be interested to know if you are successful with AMD (please feel free to reopen and comment here).
