### ISSUE TITLE
edge blend

### ISSUE THREAD

**Issue by fingerx** [jam3sward/quadifier#18]
see wiki sai:"Projector overlap, edge-blending and warping is implemented on the graphics card, using the desktop overlap and NVIDIA Warp & Blend API." Can this tool be provided?Thanks

**Comment by jam3sward** [comment]
The Warp & Blend SDK is part of NVAPI. This link has more information:
https://developer.nvidia.com/warp-and-blend

**Comment by jam3sward** [comment]
Closing this on the assumption this answered the question. Let me know otherwise.
