### ISSUE TITLE
No StereoGL in Unity 5.4

### ISSUE THREAD

**Issue by Peaj** [jam3sward/quadifier#8]
Hi James,

I tested quadifier with Unity 5.4.0f3.
Although the log seems to indicate that everything works fine I do not get a stereo effect.

I am not entirely sure that the Unity version is the problem because I hade to build with VS 2015
and had to slightly alter the project in order to compile.

It would be great if you could take a look at it. I will attach the logfile and hope it may help you.
[intercept.txt](https://github.com/jam3sward/quadifier/files/590439/intercept.txt)

Thanks,
Pascal

**Comment by jam3sward** [comment]
Hi Pascal
Are you using Unity Pro or the free version?
Also, what were the changes needed for VS 2015? (I'm still using VS 2013 here)
In the mean-time, I'll take a look at the logfile for you
Thanks
James

**Comment by Peaj** [comment]
Thanks for your fast Reply.
I have been testing in personal Edition. Since unity 5 it should not make any difference except for the unity splashscreen (which is activated).

For the Project to build in VS 2015 I had to manually download and include gltext.h and wgltext.h.
Because they are not included in Windows' OpenGL Library anymore.
There also was an ambiguous Symbol error in DLLInject.cpp. Thus I had to rename the data struct.

There may have been other small changes but I would have to compare it because I don't quite remember.

**Comment by Peaj** [comment]
Hi James,
did you find anything? Maybe you could send me a binary version built with VS 2013?
If not I could try to install the express edition and use that. I didnt think of that version before.

**Comment by jam3sward** [comment]
Hi Pascal
Sorry I've not had time to look at this yet, but in the mean-time here is a binary version built with VS 2013:
[quadifier_binaries_r72_vs2013.zip](https://github.com/jam3sward/quadifier/files/605095/quadifier_binaries_r72_vs2013.zip)
If you had it working with a previous version, then it could be the change made at 95b9b51 which requires the scripts in Unity to be updated (i.e. old scripts won't work with newer versions).
James

**Comment by Peaj** [comment]
After some testing I found that it was just the config file that has not been loaded. I did not think about that because the log looked like everything was fine. I had the file in the wrong location. Sry for the trouble. Thanks for your help and this great piece of software

**Comment by jam3sward** [comment]
Thanks for confirming the cause and for closing the issue.
It's no trouble at all, I'm just pleased to hear you have it working now!
Best regards
James
